"""Small, dependency-free configuration for the MaixCAM Pro runtime."""

CONFIG = {
    "model_path": "/root/models/yolo11n_pose.mud",
    "pose_confidence": 0.35,
    "pose_iou": 0.45,
    "keypoint_threshold": 0.35,
    "minimum_visible_keypoints": 6,
    "minimum_torso_keypoints": 3,
    "minimum_bbox_area_ratio": 0.015,
    "maximum_bbox_area_ratio": 0.80,
    "maximum_outside_ratio": 0.20,
    "duplicate_iou": 0.45,
    "duplicate_center_body_ratio": 0.25,
    "maximum_tracks": 6,
    "minimum_confirmed_hits": 2,
    "maximum_missing_seconds": 0.8,
    "smoothing_alpha": 0.55,
    "maximum_match_cost": 1.15,
    "region": (0.05, 0.05, 0.95, 0.95),
    "multi_person_seconds": 1.2,
    "phone_pose_seconds": 1.0,
    "lingering_seconds": 20.0,
    "alert_release_seconds": 0.8,
    "wrist_ear_ratio": 0.14,
    "forearm_min_ratio": 0.08,
    "torso_vertical_ratio": 0.45,
    "standing_span_ratio": 0.42,
    "lingering_max_speed_ratio": 0.12,
    "lingering_max_pose_motion_ratio": 0.04,
    "display_enabled": True,
    "event_path": "/root/poseguard_maix/data/events.jsonl",
}
